# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 854516f6809bf2d728e5b3d6d4a7cd678e87bafa65575faf7a914fee073ee5e5455e5efbd2f44a4b5b0ede92890aa6825f9fe2f70f6d18e3039df4f4ea62f810

test:
  secret_key_base: 73389fe0df6d614f9e4a1dff6f0c38d48adcf4219cc8aca913d586a51c6a51ea70965abcc2dca3a7290129012e2fcd2964c0ead3135606316eba4fb658a84cf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
